# Basic
title: 李岳
subtitle: 思想空间
welcome_message: 欢迎来到我的思想空间
description: 我是李岳，iOS / Android 开发者。
creator: <a href="http://moonlspace.com">@martinl</a>

url: "http://moonlspace.com"

permalink: /:year/:month/:title/

# Format
highlighter: plain
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: purple

blog_button:
    title: 博客
    description: 访问博客

nav:
#    - {title: 项目, description: 我的项目, url: 'http://project.onevcat.com'}
#    - {title: 关于, description: 了解更多关于我, url: 'http://about.onevcat.com/'}
#    - {title: 订阅, description: 邮件订阅本站, url: 'http://eepurl.com/wNSkj'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: maritnl
    # duoshuo:
# Social
social:
   # weibo: onevcat
   # github: onevcat
   # twitter: onevcat
   # gplus: 107108267983477358170
   # mail: onev@onevcat.com

# Google Analytics
ga:
    #id: UA-25719337-1
    #host: onevcat.com
